### ISSUE TITLE
Need separate action and more clear naming

### ISSUE THREAD

**Issue by mamaz** [prixa-ai/mili-workflow-spec#1]
I think we need to separate between `action`, `events handler`.

I also propose `process` part to run logic on certain state.

My proposal

```
mulai:
    name: "Mulai Prixa"
    flow:
      before: None
      after: consent
    process: "mulai_process:run" # process input to produce output
    action: "mulai_action:start" # do things based on output
    on:
      start: "mulai_handler:on_start"
      action: "mulai_handler:on_action"
      fail: "mulai_handler:on_fail"
```

Where `mulai_action` and `mulai_handler` is a module / package

- start
- on_start
- on_action, and
- on_fail

are functions.

Thoughts @rhzs
